# This is an example configuration file which shows what you need to add to your configuration.yaml in order to make it work
# <FHEM-IP-Address> needs to be replaced with ip address of your FHEM-instance
climate:
  - platform: fht_heating
    address: "<FHEM-IP-Address>:<port>"
    dev_name: "<FHEM-Device-Name>"
